# Generated by Django 4.2.14 on 2024-08-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_goals_monthlydata_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlydata',
            old_name='data',
            new_name='month_goals',
        ),
        migrations.AddField(
            model_name='monthlydata',
            name='current_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlydata',
            name='net_worth',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
