# Generated by Django 4.2.14 on 2024-08-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_data_monthlydata_month_goals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlydata',
            name='current_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
