# Generated by Django 4.2.14 on 2024-08-03 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_finance_month_goal_month_healthstatus_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finance',
            name='month',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='month',
        ),
        migrations.RemoveField(
            model_name='healthstatus',
            name='month',
        ),
    ]
